/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as ReglasRouteImport } from './routes/reglas'
import { Route as OportunidadesRouteImport } from './routes/oportunidades'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as EquilibrioRouteImport } from './routes/equilibrio'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ComparativaRouteImport } from './routes/comparativa'
import { Route as CarteraRouteImport } from './routes/cartera'
import { Route as CapturaRouteImport } from './routes/captura'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalisisHoraRouteImport } from './routes/analisis-hora'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksGenerateCarterasRouteImport } from './routes/api/public/hooks/generate-carteras'

const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglasRoute = ReglasRouteImport.update({
  id: '/reglas',
  path: '/reglas',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesRoute = OportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const EquilibrioRoute = EquilibrioRouteImport.update({
  id: '/equilibrio',
  path: '/equilibrio',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparativaRoute = ComparativaRouteImport.update({
  id: '/comparativa',
  path: '/comparativa',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteraRoute = CarteraRouteImport.update({
  id: '/cartera',
  path: '/cartera',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturaRoute = CapturaRouteImport.update({
  id: '/captura',
  path: '/captura',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisisHoraRoute = AnalisisHoraRouteImport.update({
  id: '/analisis-hora',
  path: '/analisis-hora',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksGenerateCarterasRoute =
  ApiPublicHooksGenerateCarterasRouteImport.update({
    id: '/api/public/hooks/generate-carteras',
    path: '/api/public/hooks/generate-carteras',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analisis-hora': typeof AnalisisHoraRoute
  '/auth': typeof AuthRoute
  '/captura': typeof CapturaRoute
  '/cartera': typeof CarteraRoute
  '/comparativa': typeof ComparativaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/equilibrio': typeof EquilibrioRoute
  '/historial': typeof HistorialRoute
  '/importar': typeof ImportarRoute
  '/oportunidades': typeof OportunidadesRoute
  '/reglas': typeof ReglasRoute
  '/reportes': typeof ReportesRoute
  '/api/public/hooks/generate-carteras': typeof ApiPublicHooksGenerateCarterasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analisis-hora': typeof AnalisisHoraRoute
  '/auth': typeof AuthRoute
  '/captura': typeof CapturaRoute
  '/cartera': typeof CarteraRoute
  '/comparativa': typeof ComparativaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/equilibrio': typeof EquilibrioRoute
  '/historial': typeof HistorialRoute
  '/importar': typeof ImportarRoute
  '/oportunidades': typeof OportunidadesRoute
  '/reglas': typeof ReglasRoute
  '/reportes': typeof ReportesRoute
  '/api/public/hooks/generate-carteras': typeof ApiPublicHooksGenerateCarterasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analisis-hora': typeof AnalisisHoraRoute
  '/auth': typeof AuthRoute
  '/captura': typeof CapturaRoute
  '/cartera': typeof CarteraRoute
  '/comparativa': typeof ComparativaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/equilibrio': typeof EquilibrioRoute
  '/historial': typeof HistorialRoute
  '/importar': typeof ImportarRoute
  '/oportunidades': typeof OportunidadesRoute
  '/reglas': typeof ReglasRoute
  '/reportes': typeof ReportesRoute
  '/api/public/hooks/generate-carteras': typeof ApiPublicHooksGenerateCarterasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/analisis-hora'
    | '/auth'
    | '/captura'
    | '/cartera'
    | '/comparativa'
    | '/configuracion'
    | '/equilibrio'
    | '/historial'
    | '/importar'
    | '/oportunidades'
    | '/reglas'
    | '/reportes'
    | '/api/public/hooks/generate-carteras'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/analisis-hora'
    | '/auth'
    | '/captura'
    | '/cartera'
    | '/comparativa'
    | '/configuracion'
    | '/equilibrio'
    | '/historial'
    | '/importar'
    | '/oportunidades'
    | '/reglas'
    | '/reportes'
    | '/api/public/hooks/generate-carteras'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/analisis-hora'
    | '/auth'
    | '/captura'
    | '/cartera'
    | '/comparativa'
    | '/configuracion'
    | '/equilibrio'
    | '/historial'
    | '/importar'
    | '/oportunidades'
    | '/reglas'
    | '/reportes'
    | '/api/public/hooks/generate-carteras'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AnalisisHoraRoute: typeof AnalisisHoraRoute
  AuthRoute: typeof AuthRoute
  CapturaRoute: typeof CapturaRoute
  CarteraRoute: typeof CarteraRoute
  ComparativaRoute: typeof ComparativaRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  EquilibrioRoute: typeof EquilibrioRoute
  HistorialRoute: typeof HistorialRoute
  ImportarRoute: typeof ImportarRoute
  OportunidadesRoute: typeof OportunidadesRoute
  ReglasRoute: typeof ReglasRoute
  ReportesRoute: typeof ReportesRoute
  ApiPublicHooksGenerateCarterasRoute: typeof ApiPublicHooksGenerateCarterasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglas': {
      id: '/reglas'
      path: '/reglas'
      fullPath: '/reglas'
      preLoaderRoute: typeof ReglasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades': {
      id: '/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof OportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equilibrio': {
      id: '/equilibrio'
      path: '/equilibrio'
      fullPath: '/equilibrio'
      preLoaderRoute: typeof EquilibrioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparativa': {
      id: '/comparativa'
      path: '/comparativa'
      fullPath: '/comparativa'
      preLoaderRoute: typeof ComparativaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartera': {
      id: '/cartera'
      path: '/cartera'
      fullPath: '/cartera'
      preLoaderRoute: typeof CarteraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captura': {
      id: '/captura'
      path: '/captura'
      fullPath: '/captura'
      preLoaderRoute: typeof CapturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisis-hora': {
      id: '/analisis-hora'
      path: '/analisis-hora'
      fullPath: '/analisis-hora'
      preLoaderRoute: typeof AnalisisHoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-carteras': {
      id: '/api/public/hooks/generate-carteras'
      path: '/api/public/hooks/generate-carteras'
      fullPath: '/api/public/hooks/generate-carteras'
      preLoaderRoute: typeof ApiPublicHooksGenerateCarterasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AnalisisHoraRoute: AnalisisHoraRoute,
  AuthRoute: AuthRoute,
  CapturaRoute: CapturaRoute,
  CarteraRoute: CarteraRoute,
  ComparativaRoute: ComparativaRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  EquilibrioRoute: EquilibrioRoute,
  HistorialRoute: HistorialRoute,
  ImportarRoute: ImportarRoute,
  OportunidadesRoute: OportunidadesRoute,
  ReglasRoute: ReglasRoute,
  ReportesRoute: ReportesRoute,
  ApiPublicHooksGenerateCarterasRoute: ApiPublicHooksGenerateCarterasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
